# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rspec', '~> 3.0'
gem 'rubocop', require: false
gem 'rubycritic', require: false
gem 'rake'
gem 'rubycritic-small-badge', :require => false
